mybets/mybets/bets/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from bets import views
from bets.views import AllBetsJson, MyCompletedBetsJson, AdminBetsJson

app_name = 'bets'
urlpatterns = [
    url(r'^$', views.bets),
    url(r'^my_bets/', views.my_bets),
    url(r'^open_bets/', views.open_bets),
    url(r'^all_bets_json/', AllBetsJson.as_view(), name='all_bets_json'),
    url(r'^my_completed_bets_json/', MyCompletedBetsJson.as_view(), name='my_completed_bets_json'),
    url(r'^admin_bets_json/', AdminBetsJson.as_view(), name='admin_bets_json'),
    url(r'^check_duplicate_bet/', views.check_duplicate_bet),
    url(r'^accept_prop_bet/', views.accept_prop_bet),
]

mybets/mybets/mybets/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic.base import RedirectView
from django.views.generic.base import TemplateView
from mybets.views import welcome, sign_up, profile

urlpatterns = [
    url(r'^favicon.ico$',
        RedirectView.as_view(
            url=staticfiles_storage.url('assets/icons/favicon.ico'),
            permanent=False),
        name="favicon"),
    url(r'^bets/', include('bets.urls', namespace='bets', app_name='bets')),
    url(r'^$', welcome),
    url(r'^login/$', auth_views.login, {'template_name': 'base_login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': '/'}, name='logout'),
    url(r'^sign_up/$', sign_up),
    url(r'^profile/', profile),
    url(r'^admin/', admin.site.urls),
]

mybets/mybets/bets/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

# Proposed Bet holds all user's prop bets, which may or may not get accepted.

class ProposedBet (models.Model):
    
    match = models.TextField()
    ods_home = models.TextField()
    ods_tie = models.TextField()
    ods_away = models.TextField()
    end_date = models.DateTimeField()
    result = models.TextField(null=True, blank=True)


    class Meta:
        ordering = ['end_date']
        verbose_name = 'Proposed Bet'
    verbose_name_plural = 'Proposed Bets'

    def __unicode__(self):
        return "{id: %d, user: '%s', prop: '%s', wager: '%d'}" % (
            self.id, self.user.get_full_name(), self.prop_text, self.prop_wager)

# Accepted bet holds all prop bets that are accepted by another user
class AcceptedBet (models.Model):
    accepted_prop = models.ForeignKey(ProposedBet)
    accepted_user = models.ForeignKey(User)
    user_od = models.TextField() #home,tie,away
    bet_amount = models.IntegerField()
    won_bet = models.TextField() #w,l

    class Meta:
        ordering = ['accepted_prop__end_date']
        verbose_name = 'Accepted Bet'
    verbose_name_plural = 'Accpeted Bets'

    def __unicode__(self):
        return "{id: %d, proposer: '%s', proposee: '%s', prop_bet: '%s', wager: '%d'}" % (self.id, self.accepted_prop.user.get_full_name(
        ), self.accepted_user.get_full_name(), self.accepted_prop.prop_text, self.accepted_prop.prop_wager)

# User Profile table holds some user info specific to this betting app

class UserProfile (models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    current_balance = models.IntegerField(
        default=0,
        help_text='The user\'s current balance. Every time the user settles up, the current balance is reset to zero.')
    overall_winnings = models.IntegerField(
        default=0, help_text='The user\'s overall winnings since joining.')
    get_prop_bet_emails = models.BooleanField(default=True)
    get_accepted_bet_emails = models.BooleanField(default=True)
    last_payment = models.DateTimeField(null=True, blank=True)
    created_on = models.DateTimeField(auto_now_add=True)
    modified_on = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'User Profile'
    verbose_name_plural = 'User Profiles'

    def __str__(self):
        return "%s Profile" % (self.user.get_full_name())

# hook user profile to user table, so that it's created when a user is created
#

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.userprofile.save()

#
# end user profile hooks

# User Profile Audit creates an audit trail each time a user's winnings
# are updated due to an accepted bet being closed.

class UserProfileAudit (models.Model):
    user = models.ForeignKey(User, related_name='user_profile_user')
    admin_user = models.ForeignKey(User, related_name='user_profile_admin')
    accepted_bet = models.ForeignKey(AcceptedBet)
    original_current_balance = models.IntegerField()
    new_current_balance = models.IntegerField()
    original_overall_winnings = models.IntegerField()
    new_overall_winnings = models.IntegerField()
    created_on = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'User Profile Audit'
    verbose_name_plural = 'User Profile Audits'

    def __str__(self):
        return "{id: %d, user: '%s', bet: '%s', orig_winnings: '%d', new_winnings: '%d'}" % (
            self.id, self.user.get_full_name(), self.accepted_bet, self.original_overall_winnings, self.new_overall_winnings)

mybets/mybets/bets/forms.py
from django import forms
from django.utils import timezone
import datetime as dt


class PlaceBetsForm(forms.Form):
    bet = forms.CharField(label='Bet', max_length=500, widget=forms.TextInput(
        attrs={'placeholder': 'E.g. Clemson -48.5 over USCjr', 'autocomplete': 'off'}))

    bet_amount = forms.IntegerField(
        label='Bet Amount (USD)',
        initial=5,
        min_value=1,
        max_value=20,
        widget=forms.TextInput(
            attrs={
                'autocomplete': 'off'}))

    qty_allowed = forms.IntegerField(
        label='Qty Allowed',
        initial=2,
        min_value=1,
        max_value=10,
        widget=forms.TextInput(
            attrs={
                'autocomplete': 'off'}))

    bet_expiration_date = forms.DateTimeField(
        label='Expiration (mm/dd/yyyy 24hr eastern time)',
        help_text='Default is one week from today. Bet will no longer be available for others to accept after this datetime.',
        widget=forms.TextInput(
            attrs={
                'autocomplete': 'off'}))

    def clean_bet_expiration_date(self):
        bet_expiration_date = self.cleaned_data['bet_expiration_date']

        if bet_expiration_date < timezone.now():
            raise forms.ValidationError("Datetime can't be in the past.")

        return bet_expiration_date

mybets/mybets/bets/views.py
import json
import requests
from django.shortcuts import render
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib import messages
from django.core.mail import send_mail
from django.contrib.sites.shortcuts import get_current_site
from django.utils import timezone
from django.views.decorators.csrf import csrf_exempt
from django_datatables_view.base_datatable_view import BaseDatatableView
from django.conf import settings
from bets.forms import PlaceBetsForm
from bets.models import ProposedBet, AcceptedBet, UserProfile, UserProfileAudit, User
from django.db.models import Sum

# Create your views here.

def bets(request):
    return HttpResponseRedirect('/bets/my_bets')



@login_required(login_url='/login/')
def my_bets(request):

    # get the current user
    current_user = request.user

    
    #your_accepted_bets = AcceptedBet.objects.select_related('accepted_prop').filter(accepted_user=current_user)

    your_accepted_bets = AcceptedBet.objects.raw("""SELECT "bets_acceptedbet"."id", "bets_acceptedbet"."accepted_prop_id", "bets_acceptedbet"."accepted_user_id", "bets_acceptedbet"."user_od", "bets_acceptedbet"."bet_amount", "bets_proposedbet"."id", "bets_proposedbet"."match", "bets_proposedbet"."ods_home", "bets_proposedbet"."ods_tie", "bets_proposedbet"."ods_away", "bets_proposedbet"."end_date", "bets_proposedbet"."result" FROM "bets_acceptedbet" INNER JOIN "bets_proposedbet" ON ("bets_acceptedbet"."accepted_prop_id" = "bets_proposedbet"."id") WHERE "bets_acceptedbet"."accepted_user_id" = 2 ORDER BY "bets_proposedbet"."end_date" ASC""")


    return render(request,
                  'bets/base_my_bets.html',
                  {'nbar': 'my_bets',
                   'your_accepted_bets': your_accepted_bets})

@login_required(login_url='/login/')
def open_bets(request):

    # used for expiring soon and new bet tags
    tomorrow = timezone.now() + timezone.timedelta(days=1)
    yesterday = timezone.now() + timezone.timedelta(days=-1)

    current_user = request.user

    open_bets = ProposedBet.objects.filter(end_date__gt = timezone.now())


    return render(request,
                  'bets/base_open_bets.html',
                  {'nbar': 'open_bets',
                   'open_bets': open_bets})


class MyCompletedBetsJson(BaseDatatableView):
    order_columns = ['accepted_prop__prop_text',
                     'accepted_prop__prop_wager', '', '']

    def get_initial_queryset(self):
        current_user = self.request.user
        your_accepted_bets = AcceptedBet.objects.filter(
            accepted_user=current_user, accepted_prop__won_bet__isnull=False)

        your_bets_accepted_by_others = AcceptedBet.objects.filter(
            accepted_prop__user=current_user, accepted_prop__won_bet__isnull=False)

        your_closed_bets = your_accepted_bets | your_bets_accepted_by_others
        return your_closed_bets.order_by('-accepted_prop__modified_on')

    def filter_queryset(self, qs):
        sSearch = self.request.GET.get(u'search[value]', None)

        if sSearch:
            qs = qs.filter(
                accepted_prop__prop_text__istartswith=sSearch) | qs.filter(
                accepted_user__first_name__istartswith=sSearch) | qs.filter(
                accepted_user__last_name__istartswith=sSearch) | qs.filter(
                accepted_prop__user__first_name__istartswith=sSearch) | qs.filter(
                    accepted_prop__user__last_name__istartswith=sSearch)

        return qs

    def prepare_results(self, qs):
        json_data = []
        current_user = self.request.user

        for item in qs:

            # figure out who the bet was against
            bet_against_user = ''
            if item.accepted_prop.user == current_user:
                bet_against_user = item.accepted_user.get_full_name()
            else:
                bet_against_user = item.accepted_prop.user.get_full_name()

            who_won = ''
            if item.accepted_prop.get_won_bet_display() == "Win":
                who_won = item.accepted_prop.user.get_full_name()
            elif item.accepted_prop.get_won_bet_display() == "Loss":
                who_won = item.accepted_user.get_full_name()
            else:
                who_won = 'push'

            json_data.append([
                item.accepted_prop.prop_text,
                '$' + str(item.accepted_prop.prop_wager),
                bet_against_user,
                who_won
            ])

        return json_data

class AllBetsJson(BaseDatatableView):
    order_columns = [
        'accepted_prop__user',
        'accepted_user',
        'accepted_prop__prop_text',
        'accepted_prop__prop_wager',
        '']

    def get_initial_queryset(self):
        return AcceptedBet.objects.filter(
            accepted_prop__won_bet__isnull=False).order_by('-accepted_prop__modified_on')

    def filter_queryset(self, qs):
        sSearch = self.request.GET.get(u'search[value]', None)

        if sSearch:
            qs = qs.filter(
                accepted_prop__prop_text__istartswith=sSearch) | qs.filter(
                accepted_user__first_name__istartswith=sSearch) | qs.filter(
                accepted_user__last_name__istartswith=sSearch) | qs.filter(
                accepted_prop__user__first_name__istartswith=sSearch) | qs.filter(
                    accepted_prop__user__last_name__istartswith=sSearch)

        return qs

    def prepare_results(self, qs):
        json_data = []
        for item in qs:

            who_won = ''
            if item.accepted_prop.get_won_bet_display() == "Win":
                who_won = item.accepted_prop.user.get_full_name()
            elif item.accepted_prop.get_won_bet_display() == "Loss":
                who_won = item.accepted_user.get_full_name()
            else:
                who_won = 'push'

            json_data.append([
                item.accepted_prop.user.get_full_name(),
                item.accepted_user.get_full_name(),
                item.accepted_prop.prop_text,
                '$' + str(item.accepted_prop.prop_wager),
                who_won
            ])

        return json_data

class AdminBetsJson(BaseDatatableView):
    order_columns = ['user', 'prop_text', '', '']

    def get_initial_queryset(self):
        closed_accepted_bets = AcceptedBet.objects.filter(
            accepted_prop__won_bet__isnull=False)
        closed_prop_bets = ProposedBet.objects.filter(
            acceptedbet__in=closed_accepted_bets).distinct().order_by('-modified_on')

        return closed_prop_bets

    def filter_queryset(self, qs):
        sSearch = self.request.GET.get(u'search[value]', None)

        if sSearch:
            qs = qs.filter(
                prop_text__istartswith=sSearch) | qs.filter(
                user__first_name__istartswith=sSearch) | qs.filter(
                user__last_name__istartswith=sSearch)

        return qs

    def prepare_results(self, qs):
        json_data = []
        for item in qs:

            completed_bet_info = [
                item.user.get_full_name(),
                item.prop_text,
                item.id]
            json_data.append([
                item.user.get_full_name(),
                item.prop_text,
                item.get_won_bet_display(),
                completed_bet_info
            ])

        return json_data


@csrf_exempt
@login_required(login_url='/login/')
def accept_prop_bet(request):
    print("In accept_prop_bet func")
    if request.method == 'POST':
        # get the prop id from the get request
        bet_id = request.POST.get('id')
        user_od = request.POST.get('user_od')
        bet_amount = request.POST.get('bet_amount')
        print("insede if",bet_id,user_od,bet_amount)
        try:
            int(bet_id)
            is_int = True

        except ValueError:
            is_int = False

        if is_int:
            # make sure bet exists
            try:
                prop_bet = ProposedBet.objects.get(id=bet_id)

            except ProposedBet.DoesNotExist:
                prop_bet = None

            # make sure bet is someone elses and it has bets left and it isn't
            # expired
            if prop_bet :

                accepted_bet = AcceptedBet(
                    accepted_prop=prop_bet,\
                    accepted_user=request.user,\
                    user_od = user_od,\
                    bet_amount = int(bet_amount))
                accepted_bet.save()

                # send a message over that the bet is accepted
                messages.success(request, 'Ставка упешно сделана!')

                # send an email to the propser, if they have their setting
                # enabled
                current_site = get_current_site(request)
                domain = current_site.domain

                
            else:
                # send a message over that there was an error
                messages.error(
                    request, 'Ошибка. Что-то пошло не так..')

        else:
            # send a message over that there was an error
            messages.error(request, 'ID ставки должно быть integer')
    else:
        # send a message over that there was an error
        messages.error(request, 'Что-то пошло не так..')

    return HttpResponseRedirect('/bets/open_bets')

@csrf_exempt
@login_required(login_url='/login/')
def check_duplicate_bet(request):

    if request.method == 'POST':
        # get the id in the post
        prop_id = request.POST.get('id')
        response_data = {}
        # check and see if this user has already accepted this bet at least
        # once
        prop_bet = ProposedBet.objects.get(id=prop_id)
        accepted_bets = AcceptedBet.objects.filter(
            accepted_prop=prop_bet, accepted_user=request.user)
        if accepted_bets:

mybets/mybets/bets/templates/bets/base_my_bets.html
{% extends "base.html" %}
{% load i18n %}

{% block extra_head %}
<script type="text/javascript">
    var MY_COMPLETED_BETS_JSON_URL = '{% url "bets:my_completed_bets_json" %}';
    // translations for datatables

    var dt_language = {
        "emptyTable":     "{% trans "Нет данных" %}",
        "infoFiltered":   "{% trans "(filtered from _MAX_ total entries)" %}",
        "infoPostFix":    "",
        "thousands":      ",",
        "lengthMenu":     "{% trans "Показать _MENU_ ставок" %}",
        "loadingRecords": "{% trans "Загрузка..." %}",
        "processing":     "{% trans "Обработка..." %}",
        "search":         "{% trans "Поиск:" %}",
        "zeroRecords":    "{% trans "Не найдено записей" %}",
        "paginate": {
            "first":      "{% trans "Первая" %}",
            "last":       "{% trans "Последняя" %}",
            "next":       "{% trans "Следующая" %}",
            "previous":   "{% trans "Предудущая" %}"
        },
        "aria": {
            "sortAscending":  "{% trans ": activate to sort column ascending" %}",
            "sortDescending": "{% trans ": activate to sort column descending" %}"
        }
    }
</script>
{% endblock %}

{% block base_content %}
<div class="container">
    <h1>Мои ставки</h1>

    <div class="container">
        <h3>Ожидающие результата:</h3>
        {% if your_accepted_bets %}
            <table class="table table-striped table-bordered table-condensed">
                <thead>
                    <tr>
                        <th>Матч</th>
                        <th>Сделанная ставка</th>
                        <th>Дата матча</th>
                    </tr>
                </thead>
                <tbody>
                    {% for bet in your_accepted_bets %}
                    <tr>
                        <td>{{ bet.match }}</td>
                        <td>{{ bet.user_od}}</td>
                        <td>{{ bet.end_date }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% else %}
            <p>У вас нет открытых ставок. Вы можете сделать ставку<a href="/bets/open_bets" data-toggle="modal"> в этом разделе</a></p>
        {% endif %}
    </div>

    
{% endblock %}

{% block morejs %}
var dt_table = $('#myCompletedBets').dataTable({
    language: dt_language,  // global variable defined in html
    order: [],
    lengthMenu: [10, 25, 50, 100],
    columnDefs: [
        {
            orderable: true,
            searchable: true,
            className: "center",
            targets: [0, 1]
        },
        {
            orderable: false,
            targets: [-1, -2]
        }
    ],
    searching: true,
    processing: true,
    serverSide: true,
    stateSave: false,
    ajax: MY_COMPLETED_BETS_JSON_URL
});

$("#remove-bet-btn").one("click", function() {
    $(this).click(function () { return false; });
});

$('#removeBet').on('show.bs.modal', function (e) {
    // get the bet text and place it in the modal
    var betText = $(e.relatedTarget).attr('data-id');
    $("#betId").html(betText);

    // get the href link with bet id and place it in the href
    $(this).find('.btn-danger').attr('href', $(e.relatedTarget).data('href'));
});
{% endblock %}

mybets/mybets/bets/templates/bets/base_open_bets.html
{% extends "base.html" %}

{% block base_content %}
<div class="container">
<h1>Предстоящие события</h1>

    <div class="container">
    {% if open_bets %}
        <table class="table table-striped table-bordered table-condensed table-responsive" id=openBets>
            <thead>
                <tr>
                    <th>Матч</th>
                    <th>Победа Хозяев</th>
                    <th>Ничья</th>
                    <th>Победа Гостей</th>
                    <th>Дата матча</th>
                </tr>
            </thead>
            <tbody>
                {% for bet in open_bets %}
                    <tr>

                    <td>{{ bet.match }}</td>
                    <td>{{ bet.ods_home }}
                    <div class="acceptBetButton" style="padding:10px 10px 0px 0px">
                                <a href="#"
                                    data-target="#acceptBet" data-toggle="modal"
                                    data-id1="{{ bet.match }}"
                                    data-id2="{{ bet.user.get_full_name }}"
                                    data-id3="{{ bet.ods_home }}"
                                    data-id4="{{ bet.id }}"
                                    title="home"
                                    class="btn btn-success btn-sm open-AcceptBet">Поставить</a>
                            </div>
                    </td>
                    <td>{{ bet.ods_tie }}
                        <div class="acceptBetButton" style="padding:10px 10px 0px 0px">
                                <a href="#" 
                                    data-target="#acceptBet" data-toggle="modal"
                                    data-id1="{{ bet.match }}"
                                    data-id2="{{ bet.user.get_full_name }}"
                                    data-id3="{{ bet.ods_tie }}"
                                    data-id4="{{ bet.id }}"
                                    title="tie"
                                    class="btn btn-success btn-sm open-AcceptBet">Поставить</a>
                            </div>
                    </td>
                    <td>{{ bet.ods_away }}
                        <div class="acceptBetButton" style="padding:10px 10px 0px 0px">
                                <a href="#" 
                                    data-target="#acceptBet" data-toggle="modal"
                                    data-id1="{{ bet.match }}"
                                    data-id2="{{ bet.user.get_full_name }}"
                                    data-id3="{{ bet.ods_away }}"
                                    data-id4="{{ bet.id }}"
                                    title="away"
                                    class="btn btn-success btn-sm open-AcceptBet">Поставить</a>
                            </div>
                    </td>
                    <td>{{ bet.end_date}}</td>

                    </tr>
                {% endfor %}
            </tbody>
        </table>
        {% else %}
            <p>Пока здесь нет событий на которые можено сделать ставку.</p>
        {% endif %}
    </div>

</div>

<!-- Accept bet modal -->
<div class="modal fade" id="acceptBet" tabindex="-1" role="dialog" aria-labelledby="AcceptBet">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="AcceptBet">Подтвердить ставку</h4>
            </div>
            <div class="modal-body">
                <span id="duplicateBet"></span>
                <p>Сделать ставку <input id = 'bet_amount' type="text" size="3"> $ с коэффициентом <span id="bet_od"></span>?
                </p>
                
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Отмена</button>
                <a class="btn btn-success" id="accept-prop-btn">Принять</a>
            </div>
        </div>
    </div>
</div>

{% endblock %}

{% block morejs %}

$('#acceptBet').on('show.bs.modal', function (e) {
    // remove any previous duplicate bet info
    $("#duplicateBet").html('');

    // get the bet text and place it in the modal
    var betText = $(e.relatedTarget).attr('data-id3');

    $("#bet_od").html(betText);

    // get the href link with bet id and place it in the href
    $(this).find('.btn-success').attr('href', $(e.relatedTarget).data('href'));

    // check to see if you've already accepted this bet
    var id = $(e.relatedTarget).attr('data-id4');

    $.ajax({
        url: '/bets/check_duplicate_bet/',
        type: 'POST',
        data: {id: id},
        success: function(json){
            console.log(json);
            if (json.is_duplicate == "True")
            {
                $("#duplicateBet").html('<div class="alert alert-info">' +
                    '<span class="glyphicon glyphicon-info-sign"></span>' +
                    'Вы уже делали ставку на это событие. ' +
                    'Вы уверены что хотите продолжить?</div>');
            }
        },
        error: function(){
            alert("issue with duplicate bet checking. id: " + id);
        }
    });

    $("#accept-prop-btn").one("click", function() {
    var user_od = $(e.relatedTarget).attr('title');
    var bet_amount = $("#bet_amount").val();
    
    $.ajax({
        url: '/bets/accept_prop_bet/',
        type: 'POST',
        data: {id: id,user_od: user_od, bet_amount: bet_amount},
        success:location.reload()
    });

    })


});

$('#openBets').dataTable( {
    "order": [],
    "paging": false
});

{% endblock %}

mybets/mybets/bets/templates/bets/place_bets.html
<!-- Place Bets Modal -->
<form class="form-horizontal" id="place-bets-form" method="post" action='{{ place_bets_form_url }}'>
    {% csrf_token %}
    <fieldset>
        {% for field in place_bets_form %}
            {% if field.errors %}
                <div class="control-group error">
                    <label class="control-label">{{ field.label }}</label>
                    <div class="controls">
                        {{ field }}
                        <p class="help-inline text-danger">
                            {% for error in  field.errors %}<strong>{{ error }}</strong>{% endfor %}
                        </p>
                    </div>
                </div>
                {% else %}
                <div class="control-group" id="place-bet-group">
                    <label class="control-label">{{ field.label }}</label>
                    <div class="controls">
                        {{ field }}
                        {% if field.help_text %}
                        <p class="help-inline"><small>{{ field.help_text }}</small></p>
                        {% endif %}
                    </div>
                </div>
            {% endif %}
        {% endfor %}
    </fieldset>
</form>