mybets/mybets/bets/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from bets import views
from bets.views import AllBetsJson, MyCompletedBetsJson, AdminBetsJson

app_name = 'bets'
urlpatterns = [
    url(r'^$', views.bets),
    url(r'^my_bets/', views.my_bets),
    url(r'^open_bets/', views.open_bets),
    url(r'^all_bets_json/', AllBetsJson.as_view(), name='all_bets_json'),
    url(r'^my_completed_bets_json/', MyCompletedBetsJson.as_view(), name='my_completed_bets_json'),
    url(r'^admin_bets_json/', AdminBetsJson.as_view(), name='admin_bets_json'),
    url(r'^check_duplicate_bet/', views.check_duplicate_bet),
    url(r'^accept_prop_bet/', views.accept_prop_bet),
]

mybets/mybets/mybets/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic.base import RedirectView
from django.views.generic.base import TemplateView
from mybets.views import welcome, sign_up, profile

urlpatterns = [
    url(r'^favicon.ico$',
        RedirectView.as_view(
            url=staticfiles_storage.url('assets/icons/favicon.ico'),
            permanent=False),
        name="favicon"),
    url(r'^bets/', include('bets.urls', namespace='bets', app_name='bets')),
    url(r'^$', welcome),
    url(r'^login/$', auth_views.login, {'template_name': 'base_login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': '/'}, name='logout'),
    url(r'^sign_up/$', sign_up),
    url(r'^profile/', profile),
    url(r'^admin/', admin.site.urls),
]

mybets/mybets/bets/forms.py
from django import forms
from django.utils import timezone
import datetime as dt


class PlaceBetsForm(forms.Form):
    bet = forms.CharField(label='Bet', max_length=500, widget=forms.TextInput(
        attrs={'placeholder': 'E.g. Clemson -48.5 over USCjr', 'autocomplete': 'off'}))

    bet_amount = forms.IntegerField(
        label='Bet Amount (USD)',
        initial=5,
        min_value=1,
        max_value=20,
        widget=forms.TextInput(
            attrs={
                'autocomplete': 'off'}))

    qty_allowed = forms.IntegerField(
        label='Qty Allowed',
        initial=2,
        min_value=1,
        max_value=10,
        widget=forms.TextInput(
            attrs={
                'autocomplete': 'off'}))

    bet_expiration_date = forms.DateTimeField(
        label='Expiration (mm/dd/yyyy 24hr eastern time)',
        help_text='Default is one week from today. Bet will no longer be available for others to accept after this datetime.',
        widget=forms.TextInput(
            attrs={
                'autocomplete': 'off'}))

    def clean_bet_expiration_date(self):
        bet_expiration_date = self.cleaned_data['bet_expiration_date']

        if bet_expiration_date < timezone.now():
            raise forms.ValidationError("Datetime can't be in the past.")

        return bet_expiration_date

mybets/mybets/templates/base.html
{% load staticfiles %}
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
        <meta name="description" content="college football betting app">
        <meta name="author" content="Josh Pelkey">
        <title>Ставки на футбол</title>
        <!-- Bootstrap core CSS -->
        <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
        <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
        <link href="{% static 'assets/css/ie10-viewport-bug-workaround.css' %}" rel="stylesheet">
        <!-- Custom styles for this template -->
        <link href="{% static 'assets/css/jumbotron.css' %}" rel="stylesheet">
        <!-- datatables css cdn -->
        <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs/jq-2.2.4/dt-1.10.15/fh-3.1.2/r-2.1.1/datatables.min.css"/>
        <!-- highcharts -->
        <script src="https://code.highcharts.com/highcharts.js"></script>
        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
        {% block extra_head %}
        {% endblock %}
    </head>

    <body>
        <nav role="navigation" class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header navbar-left pull-left">
                    <button type="button" data-toggle="collapse" data-target=".navbar-collapse" class="pull-left navbar-toggle" style="margin-left: 10px;">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    </button>
                    <a href="/" class="navbar-brand">
                    <img alt="mybets small logo" src="{% static 'assets/images/mybets_logo_sm.png' %}">
                    </a>
                </div>
                <div class="navbar-header navbar-right pull-right">
                    <ul class="nav pull-left">
                        {% if user.is_authenticated %}
                        
                        {% endif %}
                        {% if user.is_authenticated %}
                        <li class="dropdown pull-right">
                            <a href="#" data-toggle="dropdown" class="dropdown-toggle" id="profile">
                            <span class="glyphicon glyphicon-user"></span>
                            <b class="caret"></b>
                            </a>
                            <ul class="dropdown-menu">
                                <li>
                                    <div class="navbar-login">
                                        <div class="row">
                                            <div class="col-lg-4">
                                                <p class="text-center">
                                                    <span class="glyphicon glyphicon-user icon-size"></span>
                                                </p>
                                            </div>
                                            <div class="col-lg-8">
                                                <p class="text-left"><strong>{{ user.get_full_name }}</strong></p>
                                                <p class="text-left small">{{ user.email }}</p>
                                                <p class="text-left small">Ваш баланс: <strong>
                                                    {% if user.userprofile.current_balance < 0 %}
                                                        <font color="red">-${{ user.userprofile.current_balance|stringformat:"+d"|slice:"1:" }}</font>
                                                    {% elif user.userprofile.current_balance > 0 %}
                                                        <font color="green">${{ user.userprofile.current_balance }}</font>
                                                    {% else %}
                                                        ${{ user.userprofile.current_balance }}
                                                    {% endif %}
                                                    </strong>
                                                </p>
                                                <p class="text-left small">Общий выигрыш: <strong>
                                                    {% if user.userprofile.overall_winnings < 0 %}
                                                        <font color="red">-${{ user.userprofile.overall_winnings|stringformat:"+d"|slice:"1:" }}</font>
                                                    {% elif user.userprofile.overall_winnings > 0 %}
                                                        <font color="green">${{ user.userprofile.overall_winnings }}</font>
                                                    {% else %}
                                                        ${{ user.userprofile.overall_winnings }}
                                                    {% endif %}
                                                    </strong>
                                                </p>
                                                <p class="text-left">
                                                    <a href="/profile" class="btn btn-primary btn-block btn-sm">Профиль</a>
                                                </p>
                                            </div>
                                        </div>
                                    </div>
                                </li>

                                <li class="divider navbar-login-session-bg"></li>
                                {% if user.is_staff %}
                                    <li><a href="/bets/admin_bets">Admin Bets <span class="glyphicon glyphicon-thumbs-up pull-right"></span></a></li>
                                    <li class="divider"></li>
                                    <li><a href="/admin">Admin Site <span class="glyphicon glyphicon-wrench pull-right"></span></a></li>
                                    <li class="divider"></li>
                                {% endif %}

                                <!-- notifications
                                    <li><a href="#">Messages <span class="badge pull-right"> 42 </span></a></li>
                                    -->

                                <li><a href="/logout">Выйти из аккаунта<span class="glyphicon glyphicon-log-out pull-right"></span></a></li>
                            </ul>
                        </li>
                        {% endif %}
                    </ul>
                </div>
                <div class="visible-xs-block clearfix"></div>
                <div class="collapse navbar-collapse">
                    {% if user.is_authenticated %}
                        <ul class="nav navbar-nav navbar-left">
                            <li class="{% if nbar == 'my_bets' %}active{% endif %}"><a href="/bets/my_bets">Мои ставки</a></li>
                            <li class="{% if nbar == 'open_bets' %}active{% endif %}"><a href="/bets/open_bets">Открытые ставки</a></li>
                        </ul>
                    {% else %}
                        <ul class="nav navbar-nav navbar-right">
                            <li><a href="/sign_up"><span class="glyphicon glyphicon-user"></span> Зарегистрироваться</a></li>
                            <li><a href="/login"><span class="glyphicon glyphicon-log-in"></span> Войти</a></li>
                        </ul>
                    {% endif %}
                </div>
            </div>
        </nav>

        <!-- messages from django message context -->
        {% for message in messages %}
            <div class="alert {{ message.tags }} alert-dismissible" id="messages" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
                {{ message }}
            </div>
        {% endfor %}

        <!-- Main jumbotron for a primary marketing message or call to action -->
        {% block base_content %}
        <div class="jumbotron">
            <div class="container">
                <img class="img-responsive" alt="mybets main logo" src="{% static 'assets/images/mybets_logo.png' %}">
                <br/>
                <p>Base content goes here. Change it.</p>
            </div>
        </div>
        <!-- End base_content block -->
        {% endblock %}

        <!-- Place Bets form modal -->
        <div class="modal fade" id="place_bets" tabindex="-1" role="dialog" aria-labelledby="PlaceBets">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title" id="PlaceBets">Сделать ставку</h4>
                    </div>
                    <div class="modal-body">
                        {% include "bets/place_bets.html" %}
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        <button type="submit" id="place-bet-btn" class="btn btn-primary" form="place-bets-form">Подтвердить</button>
                    </div>
                </div>
            </div>
        </div>

        <hr>
        <div class="container">
            <footer>
                <p> {% now "Y" %} Федотов Артем.</p>
            </footer>
        </div>

        <!-- Bootstrap core JavaScript
            ================================================== -->
        <!-- Placed at the end of the document so the pages load faster -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
        <!-- datatables javascript cdn -->
        <script type="text/javascript" src="https://cdn.datatables.net/v/bs/jq-2.2.4/dt-1.10.15/fh-3.1.2/r-2.1.1/datatables.min.js"></script>
        <script>window.jQuery || document.write('<script src=" {% static 'assets/js/jquery.min.js' %}"><\/script>')</script>
        <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
        <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
        <script src="{% static 'assets/js/ie10-viewport-bug-workaround.js' %}"></script>
        <script type='text/javascript'>
            $(document).ready(function() {
            	$("#messages").fadeTo(3500, 500).slideUp(500, function(){
            			$("#messages").slideUp(500);
            	});

            	$('#place_bets').on('show.bs.modal', function () {
            		var d = new Date();
            		d.setDate(d.getDate() + 7)
            		var curr_date = d.getDate();
            		var curr_month = d.getMonth() + 1;
            		var curr_year = d.getFullYear();
            		$('#id_bet_expiration_date').val(curr_month + "/" + curr_date + "/" + curr_year + " 12:00");
            	});

            	$('#place-bets-form').on('submit', function(event) {
            		event.preventDefault();
            		});

            	$('#place-bets-form').one('submit', function(event) {
            		event.preventDefault();
            		$.ajax({
            			type: "POST",
            			url: this.action,
            			data: $(this).serialize(),
            			context: this,

            			success: function(data, status) {
            			window.location.href = data.url;
            			},

            			error: function(xhr, status, error) {
            				$("#place-bets-form").html(xhr.responseText);
            			}
            		});
            		return false;
            		});
            	{% block morejs %}
            	{% endblock %}
            });
        </script>
    </body>
</html>

mybets/mybets/templates/base_login.html
{% extends 'base.html' %}

{% block title %}Login{% endblock %}

{% block base_content %}
<div class="container" style="max-width: 750px;">
    {% if user.is_authenticated %}
        <h3>Вы уже зашли как {{ user.get_full_name }}.</h3>
    {% else %}
        <h2>Логин</h2>
        <p>Нужен аккаут? <a href="/sign_up"><u>Зарегистрируйтесь здесь</u></a>
        <hr>
        <form class="form-horizontal" method="post">
            {% csrf_token %}
            {% if form.non_field_errors %}
                <div class="alert alert-danger">{{ form.non_field_errors|join:"<br \>" }}</div>
            {% endif %}

            {% for field in form %}
                {% if field.errors %}
                    <div class="control-group error">
                        <label class="control-label">{{ field.label }}</label>
                        <div class="controls">
                            {{ field }}
                            <p class="help-inline text-danger">
                                {% for error in  field.errors %}<strong>{{ error }}</strong>{% endfor %}
                            </p>
                        </div>
                    </div>
                {% else %}
                    <div class="control-group">
                        <label class="control-label">{{ field.label }}</label>
                        <div class="controls">
                            {{ field }}
                            {% if field.help_text %}
                            <p class="help-inline"><small>{{ field.help_text }}</small></p>
                            {% endif %}
                        </div>
                    </div>
                {% endif %}
            {% endfor %}

            <br/>
            <div class="form-actions">
                <button type="submit" class="btn btn-primary" >Войти</button>
            </div>
        </form>

    {% endif %}

</div>
{% endblock %}

mybets/mybets/templates/base_profile.html
{% extends 'base.html' %}

{% block title %}Account Settings{% endblock %}

{% block base_content %}
<div class="container">
    <h2>Профиль</h2>

    <!-- Nav tabs -->
    <ul class="nav nav-tabs">
        <li class="active"><a data-toggle="tab" href="#user-profile">Профиль</a></li>
        <li><a data-toggle="tab" href="#user-stats">Статистика</a></li>
    </ul>
    <div class="tab-content">
        <div id="user-profile" class="tab-pane fade in active">
            <br/>
            <div "container">
                <form class="form-horizontal" id="user-profile-form" method="post" action="">
                    {% csrf_token %}
                    <fieldset>
                        {% for field in user_profile_form %}
                            {% if field.errors %}
                                <div class="control-group error">
                                    <label class="control-label">{{ field.label }}</label>
                                    <div class="controls">
                                        {{ field }}
                                        <p class="help-inline text-danger">
                                            {% for error in  field.errors %}<strong>{{ error }}</strong>{% endfor %}
                                        </p>
                                    </div>
                                </div>
                            {% else %}
                                <div class="control-group" id="user-profile-group">
                                    <label class="control-label">{{ field.label }}</label>
                                    <div class="controls">
                                        {{ field }}
                                        {% if field.help_text %}
                                        <p class="help-inline"><small>{{ field.help_text }}</small></p>
                                        {% endif %}
                                    </div>
                                </div>
                            {% endif %}
                        {% endfor %}
                    </fieldset>
                    <br/>
                    <div class="form-actions">
                        <button type="submit" class="btn btn-primary" >Сохранить</button>
                    </div>
                </form>
            </div>
        </div>

        <div id="user-stats" class="tab-pane fade">
            <br/>
            <div class="container col-md-6">
                <table class="table table-striped table-condensed">
                    <tbody>
                        <tr>
                            <td>Баланс:</td>
                            <td>
                                {% if user.userprofile.current_balance < 0 %}
                                    <font color="red">-${{ user.userprofile.current_balance|stringformat:"+d"|slice:"1:" }}</font>
                                {% elif user.userprofile.current_balance > 0 %}
                                    <font color="green">${{ user.userprofile.current_balance }}</font>
                                {% else %}
                                    ${{ user.userprofile.current_balance }}
                                {% endif %}
                            </td>
                        </tr>
                        <tr>
                            <td>Общий выигрыш:</td>
                            <td>
                                {% if user.userprofile.overall_winnings < 0 %}
                                    <font color="red">-${{ user.userprofile.overall_winnings|stringformat:"+d"|slice:"1:" }}</font>
                                {% elif user.userprofile.overall_winnings > 0 %}
                                    <font color="green">${{ user.userprofile.overall_winnings }}</font>
                                {% else %}
                                    ${{ user.userprofile.overall_winnings }}
                                {% endif %}
                            </td>
                        <tr>
                            <td>Побед:</td>
                            <td>{{ total_won_bets }}</td>
                        </tr>
                        <tr>
                            <td>Проигрышей:</td>
                            <td>{{ total_loss_bets }}</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block morejs %}
$('form')
    .each(function(){
        $(this).data('serialized', $(this).serialize())
    })
    .on('change input', function(){
        $(this)
            .find('input:submit, button:submit')
                .prop('disabled', $(this).serialize() == $(this).data('serialized'))
        ;
    })
    .find('input:submit, button:submit')
        .prop('disabled', true)
;
{% endblock %}

mybets/mybets/templates/base_sign_up.html
{% extends 'base.html' %}

{% block title %}Зарегистрироваться{% endblock %}

{% block base_content %}
<div class="container" style="max-width: 750px;margin:auto;">
    {% if user.is_authenticated %}
        <h3>You're already logged in as {{ user.get_full_name }}.</h3>
    {% else %}
        <h2>Зарегистрироваться</h2>
        <form class="form-horizontal" method="post">
            {% csrf_token %}
            <p>Все поля обязательны для заполнения. Уже зарегистрировались? <a href="/login">Войти</a></p>
            <hr>
            {% if form.errors %}
                <div class="alert alert-danger">
                    Please fix the errors below.
                    <ul>
                    {% for field in form %}
                    {% if field.errors %}
                    <li>{{ field.label }}</li>
                    {% endif %}
                    {% endfor %}
                </div>
            {% endif %}
            <div class="clearfix">
                <div class="col-md-4 form-group">
                    {{ form.first_name.label_tag }}
                    <div class="controls">
                        {{ form.first_name }}
                        <p class="help-inline text-danger"> <strong>{{ form.first_name.errors.as_text }}</strong></p>
                    </div>
                </div>
                <div class="col-md-4 col-md-offset-1 form-group">
                    {{ form.last_name.label_tag }}
                    <div class="controls">
                        {{ form.last_name }}
                        <p class="help-inline text-danger"> <strong>{{ form.last_name.errors.as_text }}</strong></p>
                    </div>
                </div>
            </div>
            <div class="clearfix">
                <div class="col-md-4 form-group">
                    {{ form.username.label_tag }}
                    <div class="controls">
                        {{ form.username }}
                        <p class="help-inline"><small>{{ form.username.help_text }}</small></p>
                        <p class="help-inline text-danger"> <strong>{{ form.username.errors.as_text }}</strong></p>
                    </div>
                </div>
                <div class="col-md-4 col-md-offset-1 form-group">
                    {{ form.group_id.label_tag }}
                    <div class="controls">
                        {{ form.group_id }}
                        <p class="help-inline"><small>{{ form.group_id.help_text }}</small></p>
                        <p class="help-inline text-danger"> <strong>{{ form.group_id.errors.as_text }}</strong></p>
                    </div>
                </div>
            </div>
            <div class="clearfix">
                <div class="col-md-4 form-group">
                    {{ form.password1.label_tag }}
                    <div class="controls">
                        {{ form.password1 }}
                        <p class="help-inline text-danger"> <strong>{{ form.password1.errors.as_text }}</strong></p>
                    </div>
                </div>
                <div class="col-md-4 col-md-offset-1 form-group">
                    {{ form.password2.label_tag }}
                    <div class="controls">
                        {{ form.password2 }}
                        <p class="help-inline text-danger"> <strong>{{ form.password2.errors.as_text }}</strong></p>
                    </div>
                </div>
            </div>
            <br/>
            <div class="form-actions">
                <button type="submit" class="btn btn-primary" >Зарегистрироваться</button>
            </div>
        </form>
    {% endif %}
</div>
{% endblock %}